### register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "fullName": "huhuhuhuhuhu",
  "email": "huhuhuhu@gmail.com",
  "password": "huhuhuhu",
  "role": "user"
}


### Login to get token
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "huhuhuhu@gmail.com",
    "password": "huhuhuhu"
}