### user get address info
POST http://localhost:3000/api/user/get-address-info
Content-Type: application/json

{ 
    "type": "district", 
    "parentCode": "001"
}


### get user by id
POST http://localhost:3000/api/user/get-user-by-id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MDY4MTgzYjM3ZWVjZmNiMDNhZDJhNCIsImlhdCI6MTc0NTU2NTI5MywiZXhwIjoxNzQ1NjUxNjkzfQ.AqzixOLvCRuBCh9fWV7G9T-du_7XfUmt0QYAQZRsA-s

{
    "id": "68068183b37eecfcb03ad2a4"
}